/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#777587",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed": "#121f00",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "on-error-container": "#93000a",
        secondary: "#831ada",
        "on-tertiary-container": "#abef3e",
        "secondary-fixed": "#f0dbff",
        "on-secondary": "#ffffff",
        background: "#faf8ff",
        "on-primary-container": "#dad7ff",
        "error-container": "#ffdad6",
        tertiary: "#345000",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#ddb8ff",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#98da27",
        "surface-container-low": "#f2f3ff",
        "secondary-container": "#9e41f5",
        "on-tertiary-fixed-variant": "#334f00",
        "on-surface": "#131b2e",
        "on-primary-fixed-variant": "#3323cc",
        "surface-bright": "#faf8ff",
        "inverse-primary": "#c3c0ff",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "on-error": "#ffffff",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4d44e3",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#eef0ff",
        "tertiary-container": "#466a00",
        "on-primary": "#ffffff",
        primary: "#3525cd",
        "tertiary-fixed": "#b2f746",
        "on-secondary-fixed": "#2c0051",
        "outline-variant": "#c7c4d8",
        surface: "#faf8ff",
        "on-secondary-fixed-variant": "#6800b4",
        "surface-dim": "#d2d9f4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        md: "16px",
        gutter: "24px",
        sm: "8px",
        xl: "40px",
        "container-max": "1280px",
        unit: "4px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
